### ISSUE TITLE
nigga i got bagged at school

### ISSUE THREAD

**Issue by doubleglocks** [6nz/virustotal-vm-blacklist#1]

**Comment by doubleglocks** [comment]
fuck that black bitch who decided to only search me bruhh

**Comment by doubleglocks** [comment]
> fuck that black bitch who decided to only search me bruhh

im on the shitty school laptops bruh im not going home im finna go home & get my laptop & im out that hoe 😭

**Comment by 6nz** [comment]
LMFAO

**Comment by doubleglocks** [comment]
> LMFAO

im finna go home get my macbook & other shit & dip

**Comment by doubleglocks** [comment]
> LMFAO

i say we do a bit of trolling on my schools emails & website 😂

**Comment by doubleglocks** [comment]
> LMFAO

give me the virus shit ima run it on my school computer

**Comment by 6nz** [comment]
Its on my github py stealer

**Comment by 6nz** [comment]
Download the release

**Comment by 6nz** [comment]
> Might not work btw but u can try it

**Comment by doubleglocks** [comment]
> > Might not work btw but u can try it

ai bet ima do that shit when i get home LOOOOOOOOOOOOL

**Comment by doubleglocks** [comment]
> > Might not work btw but u can try it

nigga i got the best seat in the iss room

**Comment by 6nz** [comment]
Hi

**Comment by doubleglocks** [comment]
> Hi

sup
