### ISSUE TITLE
cpu serial

### ISSUE THREAD

**Issue by sea256** [6nz/virustotal-vm-blacklist#11]
"To Be Filled By O.E.M."
Found on an ordinary machine, definetely not VM/sandbox

**Comment by 6nz** [comment]
I will edit the list manually.

**Comment by 6nz** [comment]
Thanks for the comment

**Comment by 6nz** [comment]
Frank VM machine actually uses "to be filled by oem" for cpuid: but I have removed it from the list. It might get on the list later again...
