### ISSUE TITLE
Organize this

### ISSUE THREAD

**Issue by b6m** [6nz/virustotal-vm-blacklist#2]
Hiya, I think it'd be alot better if u made folder for each category and then put the files for it in the folder for example
Gpu
   gpus.py
Ips
  ips.py

and so on.

**Comment by b6m** [comment]
i meant to type txt and not ip 😅

**Comment by 6nz** [comment]
I would have to re write my programs, might do it later

**Comment by 6nz** [comment]
We will see

**Comment by 6nz** [comment]
Cuz other people using that blacklist too

**Comment by 6nz** [comment]
It would break the program

**Comment by b6m** [comment]
wel, u/they would simply have to change the link

**Comment by 6nz** [comment]
> wel, u/they would simply have to change the link

Well ye true
