### ISSUE TITLE
Super small list. We literally have a list with over 2k machines open-source, lmao

### ISSUE THREAD

**Issue by ClaraCrazy** [6nz/virustotal-vm-blacklist#4]
kekw

**Comment by 6nz** [comment]
this list only contains virustotal machines

**Comment by 6nz** [comment]
the most important is the GPU blacklist and my anti dbg program not the whole hwid,ip list etc

**Comment by 6nz** [comment]
and vt doesnt have 2k+ machines

**Comment by 6nz** [comment]
@ClaraCrazy  drop a link to ur list then

**Comment by ClaraCrazy** [comment]
So does our list.

----

Also, your GPU list isn't complete either. I have seen other projects inspired by my organization's code that have already over 70-80 GPUs, not to mention our list.

----

Fun fact, VT has over 25k machines if you were to read their announcements, etc. Not to mention all the linked MS-S & Zboxes and all their other 2nd hand scanner boxes they own administrative rights over. You seem to not know very much about VirusTotal, probably not even in their insider program or the Intelligence community. But that's okay. We all start somewhere

----

And if you are too slow to follow a profile trace, then I'm afraid I won't be able to help you either. I'm not going to spoonfeed a script kiddy, nor will anyone else

----

Lastly, I just want you to have a nice day.

~ Clara K - CynthiaLabs

**Comment by 6nz** [comment]
> So does our list.
> 
> ----
> 
> Also, your GPU list isn't complete either. I have seen other projects inspired by my organization's code that have already over 70-80 GPUs, not to mention our list.
> 
> ----
> 
> Fun fact, VT has over 25k machines if you were to read their announcements, etc. Not to mention all the linked MS-S & Zboxes and all their other 2nd hand scanner boxes they own administrative rights over. You seem to not know very much about VirusTotal, probably not even in their insider program or the Intelligence community. But that's okay. We all start somewhere
> 
> ----
> 
> And if you are too slow to follow a profile trace, then I'm afraid I won't be able to help you either. I'm not going to spoonfeed a script kiddy, nor will anyone else
> 
> ----
> 
> Lastly, I just want you to have a nice day.
> 
> ~ Clara K - CynthiaLabs

Send me the list already

**Comment by 6nz** [comment]
U showed no proof

**Comment by 6nz** [comment]
Yet

**Comment by 6nz** [comment]
im not here to copy ur list

**Comment by 6nz** [comment]
Yep. Ur prolly lying + idgaf
